# Generated by Django 6.1 on 2026-09-08 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cleaning Add-on / Surcharge',
                'verbose_name_plural': 'Cleaning Add-ons / Surcharges',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='CleaningServiceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('regular', 'Limpieza Regular'), ('deep', 'Limpieza Profunda (GoFurther)'), ('move_in_out', 'Limpieza MoveIn/MoveOut'), ('post_construction', 'Limpieza Post-Construcción')], max_length=30, unique=True)),
                ('rate_per_sqft', models.DecimalField(decimal_places=4, help_text='Rate per square foot (e.g. 0.1000 for $0.10/sqft)', max_digits=6)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=99.0, help_text='Minimum service fee threshold in USD', max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cleaning Service Rate',
                'verbose_name_plural': 'Cleaning Service Rates',
                'ordering': ['rate_per_sqft'],
            },
        ),
        migrations.CreateModel(
            name='CleaningOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_first_name', models.CharField(blank=True, max_length=100)),
                ('guest_last_name', models.CharField(blank=True, max_length=100)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(default='Denver', max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('delivery_zone', models.CharField(choices=[('inner', 'Denver & Boulder Metro (FREE)'), ('outer', 'Outer Zone ($25 Fee)')], default='inner', max_length=20)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('square_feet', models.PositiveIntegerField(default=1000, help_text='Property size in square feet')),
                ('selected_addons', models.JSONField(blank=True, default=list, help_text='List of selected addon objects or codes')),
                ('service_date', models.DateField(help_text='Scheduled date for cleaning service')),
                ('time_slot', models.CharField(choices=[('morning', 'Morning (8:00 AM - 12:00 PM)'), ('afternoon', 'Afternoon (1:00 PM - 5:00 PM)')], max_length=20)),
                ('special_instructions', models.TextField(blank=True, help_text='Property access, gate codes or special notes')),
                ('base_price', models.DecimalField(decimal_places=2, default=99.0, max_digits=8)),
                ('addons_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, default=99.0, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_orders', to=settings.AUTH_USER_MODEL)),
                ('service_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cleaning.cleaningservicerate')),
            ],
            options={
                'verbose_name': 'Cleaning Order',
                'verbose_name_plural': 'Cleaning Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
