# Generated by Django 6.1 on 2026-09-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningservicerate',
            name='rate_per_sqft',
            field=models.DecimalField(decimal_places=2, help_text='Rate per square foot (e.g. 0.10 for $0.10/sqft)', max_digits=6),
        ),
    ]
