# Generated by Django 6.1 on 2026-09-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0002_alter_cleaningservicerate_rate_per_sqft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleaningaddon',
            options={'ordering': ['price'], 'verbose_name': 'Cleaning Add-on', 'verbose_name_plural': 'Cleaning Add-ons'},
        ),
        migrations.AddField(
            model_name='cleaningorder',
            name='brand',
            field=models.CharField(blank=True, choices=[('gopropertycare', 'GoPropertyCare'), ('evolvingsolutions', 'Evolving Solutions LLC')], default='gopropertycare', max_length=30),
        ),
        migrations.AlterField(
            model_name='cleaningorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='cleaningservicerate',
            name='service_type',
            field=models.CharField(choices=[('regular', 'Limpieza Regular'), ('deep', 'Limpieza Profunda (GoFurther)'), ('move_in_out', 'Limpieza MoveIn/MoveOut'), ('post_construction', 'Limpieza Post-Construcción'), ('commercial', 'Limpieza Comercial / Janitorial'), ('industrial_demolition', 'Demolición de Drywall y Mano de Obra Industrial')], max_length=30, unique=True),
        ),
    ]
