# Generated by Django 6.1 on 2026-09-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0003_alter_cleaningaddon_options_cleaningorder_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningaddon',
            name='brand',
            field=models.CharField(choices=[('gopropertycare', 'GoPropertyCare (Residential)'), ('evolvingsolutions', 'Evolving Solutions LLC (Commercial)'), ('both', 'Both Brands')], default='gopropertycare', help_text='Target brand for this add-on', max_length=30),
        ),
        migrations.AddField(
            model_name='cleaningservicerate',
            name='brand',
            field=models.CharField(choices=[('gopropertycare', 'GoPropertyCare (Residential)'), ('evolvingsolutions', 'Evolving Solutions LLC (Commercial & Post-Construction)')], default='gopropertycare', help_text='Brand providing this service', max_length=30),
        ),
        migrations.AlterField(
            model_name='cleaningaddon',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='cleaningaddon',
            constraint=models.UniqueConstraint(fields=('code', 'brand'), name='unique_addon_code_per_brand'),
        ),
    ]
