# Generated by Django 6.1.2 on 2026-10-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0004_cleaningaddon_brand_cleaningservicerate_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningservicerate',
            name='service_type',
            field=models.CharField(choices=[('residential', 'Residential Cleaning'), ('move_in_out', 'Move-In / Move-Out Cleaning'), ('commercial', 'Commercial Cleaning'), ('post_construction', 'Post-Construction Cleaning'), ('short_term_rental', 'Short-Term Rentals Turnover (Airbnb / VRBO)'), ('regular', 'Limpieza Regular'), ('deep', 'Limpieza Profunda (GoFurther)'), ('industrial_demolition', 'Demolición de Drywall y Mano de Obra Industrial')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='cleaningservicerate',
            constraint=models.UniqueConstraint(fields=('service_type', 'brand'), name='unique_service_type_per_brand'),
        ),
    ]
