# Generated by Django 6.1.2 on 2026-10-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0005_alter_cleaningservicerate_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningorder',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, default=1.0, help_text='Number of bathrooms', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cleaningorder',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Number of bedrooms', null=True),
        ),
        migrations.AddField(
            model_name='cleaningorder',
            name='entry_method',
            field=models.CharField(blank=True, default='someone_home', help_text='Access method', max_length=50),
        ),
        migrations.AddField(
            model_name='cleaningorder',
            name='entry_notes',
            field=models.CharField(blank=True, help_text='Access code or key notes', max_length=255),
        ),
        migrations.AddField(
            model_name='cleaningorder',
            name='is_occupied',
            field=models.BooleanField(default=True, help_text='Whether property is occupied/furnished or vacant'),
        ),
        migrations.AlterField(
            model_name='cleaningorder',
            name='time_slot',
            field=models.CharField(help_text='Selected time or window (e.g. 02:00 PM, morning, afternoon)', max_length=50),
        ),
        migrations.AlterField(
            model_name='cleaningservicerate',
            name='rate_per_sqft',
            field=models.DecimalField(decimal_places=3, help_text='Rate per square foot (e.g. 0.125 for $0.125/sqft)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='cleaningservicerate',
            name='service_type',
            field=models.CharField(choices=[('residential', 'Basic Residential Cleaning'), ('move_in_out', 'Move In / Out Cleaning'), ('str_on_site', 'Short Term Rentals (Laundry on site)'), ('str_off_site', 'Short Term Rentals (Off Site Laundry)'), ('short_term_rental', 'Short-Term Rentals Turnover (Airbnb / VRBO)'), ('commercial', 'Commercial Cleaning'), ('post_construction', 'Post-Construction Cleaning'), ('regular', 'Limpieza Regular'), ('deep', 'Limpieza Profunda (GoFurther)'), ('industrial_demolition', 'Demolición de Drywall y Mano de Obra Industrial')], max_length=30),
        ),
    ]
