# Generated by Django 6.1 on 2026-08-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_first_name', models.CharField(blank=True, max_length=100)),
                ('guest_last_name', models.CharField(blank=True, max_length=100)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('pickup_date', models.DateField()),
                ('pickup_time_slot', models.CharField(choices=[('morning', 'Morning (8AM - 11AM)'), ('afternoon', 'Afternoon (12PM - 4PM)')], max_length=20)),
                ('order_details', models.TextField(help_text='Details about the laundry order')),
                ('pickup_instructions', models.TextField(blank=True, help_text='Special instructions for pickup')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready', 'Ready for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('next_pickup_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Recurring Schedule',
                'verbose_name_plural': 'Recurring Schedules',
            },
        ),
        migrations.CreateModel(
            name='ServiceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('standard', 'Standard (2 days)'), ('go', 'Go (Next day)'), ('gofurther', 'GoFurther (Same day)')], max_length=20, unique=True)),
                ('rate_per_lb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('delivery_days', models.IntegerField(help_text='Number of days for delivery')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Rate',
                'verbose_name_plural': 'Service Rates',
                'ordering': ['delivery_days'],
            },
        ),
    ]
