# Generated by Django 6.1 on 2026-09-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_city_order_delivery_fee_order_delivery_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringschedule',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], max_length=20),
        ),
    ]
