# Generated by Django 6.1 on 2026-09-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_recurringschedule_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=10),
        ),
    ]
